title: 3fun4's Blog
logo: /assets/img/logo.png
description: using [Minimal theme](https://pages-themes.github.io/minimal/).
show_downloads: false
# remote_theme: "mmistakes/minimal-mistakes"
# plugins:
#  - jekyll-mentions
#  - jemoji
#  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-remote-theme
theme: jekyll-theme-minimal
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
kramdown:
  parse_block_html: true